### ISSUE TITLE
Severe lag when going above Y180

### ISSUE THREAD

**Issue by Revvilo** [fredtargaryen/Rocket-Squids#1]
A weird problem seemingly caused by the rapid respawning of entities when you're above Y level 180 that causes extreme fps loss.

1. Open SP with Rocket Squids
2. Find an ocean
3. Fly above Y level 180
4. RIP FPS

- Rocket Squids Version: 1.0 (Installed via the Curse/Twitch client, possibly out of date?)
- Forge Version: 12.18.3.2281

**Comment by fredtargaryen** [comment]
Thanks for reporting this. I don't think I'd ever have found it - my framerate is terrible all the time (though I suspect that's more to do with my laptop than the mod). Looking into it now.

By the way, 1.0 is actually the latest version.

**Comment by fredtargaryen** [comment]
Hi, hope you're still available to discuss this. I can see the issue you're reporting. It would speed up the bugfixing if you could please let me know: what makes you think it is to do with rapid respawning of entities?
Edit: Never mind, it definitely is. I will try and do something about this, but in the meantime, spawning seems to work normally if your render distance is below 10.

**Comment by Revvilo** [comment]
Sorry, I've been away for a bit and haven't been online.
It was just to do with the way JourneyMap showed the entities flickering as well as the information I found about the way entities rapidly respawn when above y180.
No worries though, I understand if it's hard to diagnose because it sounds like quite a complicated issue.

**Comment by fredtargaryen** [comment]
I might have found the solution to this, but frankly my FPS tanks when I fly upwards in any case so I can't tell for sure if I've fixed it. I can provide an early build if you want to see for yourself.

**Comment by fredtargaryen** [comment]
Tried the mod on my new PC, no lag issues. I consider this closed now; thank you!
