### ISSUE TITLE
Incompatible with Forge v28.1.1

### ISSUE THREAD

**Issue by WenXin20** [fredtargaryen/Rocket-Squids#12]
Minecraft v1.14.4
Forge v28.1.1
Rocket Squids v1.2

The game won't start when using the newest Forge v28.1.1

```[15:39:41] [main/ERROR]: Missing language javafml version [28,28] wanted by Rocket Squids 1.14.4-1.2.jar, found 28.1```

![image](https://user-images.githubusercontent.com/12000593/64893712-66597a80-d63d-11e9-9529-cde2f550a26d.png)

**Comment by fredtargaryen** [comment]
Hi! This will be dealt with by the next version. Thanks for reporting!
