### ISSUE TITLE
Crash w/ Optifine

### ISSUE THREAD

**Issue by WenXin20** [fredtargaryen/Rocket-Squids#13]
Minecraft v1.14.4
Forge v28.1.26
Rocket Squids v1.2
Optifine vHD_U_F4_pre5

I received the following crash almost immediately at game launch.
[Crash Report](https://gist.github.com/WenXin20/bea2306b9bb1b5b9afbb6c423fd513fd)

**Comment by fredtargaryen** [comment]
Hi; thanks for reporting!

I have this on my other two mods as well. This is because they are made for Forge 28.1.0 and above, whereas Optifine is currently only compatible with version 28.0.93, As such i won't be fixing this one.

**Comment by WenXin20** [comment]
Optifine vHD_U_F4_pre6 just put out an update to support forge v28.1.26, but I still get the same crash.

**Comment by fredtargaryen** [comment]
Closed; Optifine plays nicely with particles as of F4_pre9.
