### ISSUE TITLE
Rocket squids spawn outside of water

### ISSUE THREAD

**Issue by SissyTrashQueen** [fredtargaryen/Rocket-Squids#14]
I noticed an issue when near a river biome that doesnt have water in it, the rocket squids spawn there to just die. Regarding this same issue, rocket squids also spawn underground river biomes.

**Comment by fredtargaryen** [comment]
Hi; thanks for reporting!
I don't see anything wrong with spawning in underground rivers, but spawning outside water is no good. I'll look into that.

**Comment by SissyTrashQueen** [comment]
By underground river biome, i meant outside of water aswell on a cave. Thanks for your response! :)

**Comment by fredtargaryen** [comment]
Hi again! Please could you try [this version](https://fredtargaryen.github.io/files/Rocket%20Squids%201.14.4-1.2.jar?raw=true) and see if you're still having the same problem?

**Comment by SissyTrashQueen** [comment]
I have just tried it, and it seems to work fine now, ty! :)

**Comment by fredtargaryen** [comment]
Lovely stuff. Thanks again!
