### ISSUE TITLE
Better Config

### ISSUE THREAD

**Issue by mxnmnm** [fredtargaryen/Rocket-Squids#16]
Would it be possible to have a config for the world gen such as the conches? I don't want them spawning in specific dimensions, so being able to whitelist/blacklist dimensions would be very nice. The same should go for the squid statues as well.

**Comment by fredtargaryen** [comment]
Very good point! Something I should have thought about from the beginning. I'll get on that.

**Comment by mxnmnm** [comment]
Can the new config options be for 1.12 as well as the later versions?

**Comment by fredtargaryen** [comment]
I don't have as much time as I used to so my policy is that I put new features in the latest version and do bugfix support for the previous version. Previous versions, contributions are welcome but I can't bring them up to speed with the others by myself. If it turns out very easy to backport I might make an exception but don't expect any miracles...

**Comment by fredtargaryen** [comment]
The dimensions in which conches and statues generate is now configurable in 1.16.3. [Here's a link if you want to try it](https://www.curseforge.com/minecraft/mc-mods/rocket-squids/files/3126564). I'll try and backport this as far back as I can be bothered.

**Comment by fredtargaryen** [comment]
I've roughly backported this to 1.12.2; [Here's the link for that](https://www.curseforge.com/minecraft/mc-mods/rocket-squids/files/3132074). I'm only giving this until Friday for feedback; then I don't want to touch 1.12.2 for my mods ever again!

**Comment by mxnmnm** [comment]
Yep it works like a charm! On a side note, what's up with the statues? I remember accidentally opening one but I can't remember what I did to open it. So how do you open them? Thanks!

**Comment by fredtargaryen** [comment]
Great news; thanks for confirming! If you look carefully at the front of the statue, at the base, you should see a slight imprint where a certain item would fit nicely!
