### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by Versus506** [fredtargaryen/Rocket-Squids#2]
Probably incompatible with something i added yesterday
https://pastebin.com/xvd2a5E7

**Comment by fredtargaryen** [comment]
Wow, a crash that tells me not to do what I did. Will hopefully have a fix within the week. Thanks!

**Comment by Versus506** [comment]
Thanks!

**Comment by fredtargaryen** [comment]
Seems to work now. Fixes for 1.12.2 and 1.11.2 will be out today.
