### ISSUE TITLE
[1.12.2-1.0.1] Missing localizations

### ISSUE THREAD

**Issue by Lykrast** [fredtargaryen/Rocket-Squids#3]
None of the items or mobs have a localized name in the latest public version.

![image](https://user-images.githubusercontent.com/8684850/44620887-9dc38080-a89c-11e8-956b-2f9c6b957af1.png)
![image](https://user-images.githubusercontent.com/8684850/44620888-a2883480-a89c-11e8-8403-0c13b9377e23.png)
![image](https://user-images.githubusercontent.com/8684850/44620891-acaa3300-a89c-11e8-8d52-e07f57025c18.png)

**Comment by fredtargaryen** [comment]
That's really strange. I don't know why the .lang files saved that way, but until I release a new version, a quick fix is to open the mod .jar, go to assets/ftrsquids/lang and rename en_US.lang to en_us.lang (or gb if you prefer)

Uploaded v1.12.2-1.0.2; should be approved in a few hours.

**Comment by fredtargaryen** [comment]
Looks like this isn't a problem any more, so I will go ahead and close this one.
