### ISSUE TITLE
Config

### ISSUE THREAD

**Issue by regakakobigman** [fredtargaryen/Rocket-Squids#4]
Hey, the current filename for the config is ftrsquids.cfg. Could this be changed to something like rocketsquids.cfg? I looked for files starting with `r` but I didn't find it there. In Windows, `*squid*` in Explorer or `dir *squid*` can find it easily, but I accidentally searched for `squid` instead and didn't find it. I felt a little silly when I found the config after thinking there wasn't one. A change like this could help dumbos like me.

Changing the name of the config wouldn't prevent me from messing up Windows search, but it would make it easier to find the config right away by being closer to the mod's name.

Thanks!

**Comment by fredtargaryen** [comment]
Hi. I've always tried to put "ft" at the start of my mod IDs in case people install two mods with the same name, but yeah, that wasn't very sensible.

How is "rocketsquidsft.cfg"? I'll probably change this for my other mods too.

**Comment by regakakobigman** [comment]
That'd be perfect.

**Comment by fredtargaryen** [comment]
OK, it will be rocketsquidsft.cfg in all _future_ versions of the mod. Unfortunately any changes to ftrsquids.cfg won't be transferred to the new config file. Cheers!
